const GETFULLHEIGHT = 'GETFULLHEIGHT';
const GETASIDEEL = 'GETASIDEEL';
const SETASIDESTATE = 'SETASIDESTATE';
const GETLAYOUTEL = 'GETLAYOUTEL';
const MAINCONTAINEREL = 'MAINCONTAINEREL';
const GETTOPEL = 'GETTOPEL';
const GETSWITCHESEL = 'GETSWITCHESEL';
const SCROLLABLE = 'SCROLLABLE';
const SCROLLDISABLE = 'SCROLLDISABLE';
const DARKSTYLE = 'DARKSTYLE';
const WHITESTYLE = 'WHITESTYLE';
const LOGOSYMBOLEL = 'LOGOSYMBOLEL';
const LOGOTEXTEL = 'LOGOTEXTEL';
const CURRTHEME='CURRTHEME';
export default {
    GETFULLHEIGHT,
    GETASIDEEL,
    SETASIDESTATE,
    GETLAYOUTEL,
    MAINCONTAINEREL,
    GETTOPEL,
    SCROLLABLE,
    SCROLLDISABLE,
    DARKSTYLE,
    WHITESTYLE,
    GETSWITCHESEL,
    LOGOSYMBOLEL,
    LOGOTEXTEL,
    CURRTHEME
}
